quarkus.datasource.db-kind=h2
quarkus.datasource.username=${DB_USERNAME:sa}
quarkus.datasource.password=${DB_PASSWORD:}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:h2:mem:cinema;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR}
# Optional configuration
quarkus.hibernate-orm.sql-load-script=META-INF/import.sql
quarkus.hibernate-orm.database.generation=${DB_SCHEMA_STRATEGY:drop-and-create}

quarkus.infinispan-client.hosts=${INFINISPAN_HOSTS:localhost:11222}
quarkus.infinispan-client.use-auth=${INFINISPAN_USE_AUTH:true}
quarkus.infinispan-client.username=${INFINISPAN_USERNAME:developer}
quarkus.infinispan-client.password=${INFINISPAN_PASSWORD:XPdwODnIDIyrMvyb}

quarkus.infinispan-client.trust-store=${INFINISPAN_TRUSTSTORE:/deployments/tls/tls.crt}
quarkus.infinispan-client.trust-store-type=${INFINISPAN_TRUSTSTORE_TYPE:pem}
quarkus.infinispan-client.sni-host-name=${INFINISPAN_SNI_HOST:}
